=== LS05/Agroludos/src/main/java/agroludos/presentation/reqresh/ReqFactorySchema.xsd
<?xml version="1.0"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="richieste">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="richiesta" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:integer" name="classe"/>
            </xs:sequence>
            <xs:attribute type="xs:string" name="tipo" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== LS05/Agroludos/src/main/java/agroludos/presentation/reqh/RequestFactory.xml
<?xml version="1.0" encoding="UTF-8"?>
<richieste xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="ReqFactorySchema.xsd">
	<richiesta tipo="checkConfigurazione">
		<classe>agroludos.presentation.reqh.EmptyRequestContextImpl</classe>
	</richiesta>
	<richiesta tipo="confermaConfigurazione">
		<classe>agroludos.presentation.reqh.DataRequestContextImpl</classe>
	</richiesta>
	<richiesta tipo="nuovoManagerDiSistema">
		<classe>agroludos.presentation.reqh.DataRequestContextImpl</classe>
	</richiesta>
	<richiesta tipo="autenticazioneUtente">
		<classe>agroludos.presentation.reqh.DataRequestContextImpl</classe>
	</richiesta>
</richieste>
